name = "UnregisteredA"
uuid = "b686e103-ce6e-4868-bd28-4023dc495743"
authors = ["David Varela <00.varela.david@gmail.com>"]
version = "0.2.0"

[deps]
UnregisteredB = "4a15487d-6a03-40fd-be4e-f31ac6f07bdf"

[source]
UnregisteredB = "https://github.com/00vareladavid/UnregisteredB"
